// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qddyuheyrlqgmqhwnjkb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFkZHl1aGV5cmxxZ21xaHduamtiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5MDM2NTcsImV4cCI6MjA2MDQ3OTY1N30.DP-4pbo2EvS2oqQNvTUqwFCFWjZVQNdMcBGL773tmdg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);